vich_uploader:
    db_driver: orm
    mappings:
        vehicle_image:
            uri_prefix: '%app.path.vehicles_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.vehicles_images%'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'spz'}
            inject_on_load: false
            delete_on_update: false # nechceme, aby nám po updatování obrázku odstranil původní obrázek
            delete_on_remove: false # nechceme, aby se po smazání entity odstranil původní obrázek