version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./symfony/:/var/www/symfony/
    ports:
      - 8001:80
    networks:
      - symfony
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    environment:
      APP_ENV: dev
    volumes:
      - ./symfony/:/var/www/symfony/
    networks:
      - symfony

networks:
  symfony: